Workon modification
Overview:
1. There is a bug, that even if any step failed in workon, it will
   continue to do workon and finally complete the workon. if anyone
   tried to build after this, they will see build failure.
2. It will fail to workon, if RH8 machine doesn't have scl support.
3. Python venv will take lot of time in grid machines.

- SBE workon default support python3 (Fallback machanism also
  supported), Check the python3 avaliablility in machine switch
  to python2(scl) which invoke the python3
- Any failure while workon, exit from workon (bugfix)
- By removing the venv concept and install python packages to
  default user location, it solves the 3rd issues
- Depend on python version modify PYHOTNUSERBASE

Change-Id: If49164d6469601c18dfb18fafa5953e26b6455d0
Reviewed-on: http://rchgit01.rchland.ibm.com/gerrit1/146678
Tested-by: Jenkins Server <pfd-jenkins+hostboot@us.ibm.com>
Reviewed-by: Rajees P P <rajerpp1@in.ibm.com>
Reviewed-by: Ramesh I <rameshi1@in.ibm.com>
Reviewed-by: Ilya Smirnov <ismirno@us.ibm.com>
Reviewed-by: Sunil Kumar <skumar8j@in.ibm.com>

diff --git a/public/src/tools/utils/sbe/sbe-workon-utils b/public/src/tools/utils/sbe/sbe-workon-utils
--- a/public/src/tools/utils/sbe/sbe-workon-utils
+++ b/public/src/tools/utils/sbe/sbe-workon-utils
@@ -2,7 +2,7 @@
 # IBM_PROLOG_BEGIN_TAG
 # This is an automatically generated prolog.
 #
-# $Source: public/src/tools/utils/sbe/venv-python $
+# $Source: public/src/tools/utils/sbe/sbe-workon-utils $
 #
 # OpenPOWER sbe Project
 #
@@ -31,48 +31,51 @@ source public/src/tools/utils/sbe/detect-python
 swapingNewShell()
 {
     PYTHON_VERSION=$(get_python_version)
+    echo "Python Version: $PYTHON_VERSION"
 
     # For machines which have python2 as default(mostly all CI machines)
     # execute scl command. Do nothing if python3 is default.
-    if [ "$PYTHON_VERSION" == "3" ]; then
-        export SCL_PYTHON_ENABLED=0
+    if [[ "$PYTHON_VERSION" == "3" ]]; then
         echo "***INFO | Machine has Python3 as default"
         echo "Spawning new shell (/bin/bash)..."
-        bash --rcfile ./env.bash -i
-    elif [ "$PYTHON_VERSION" == "2" ]; then
-        export SCL_PYTHON_ENABLED=1
+        export SCL_PYTHON_ENABLED=0
+        bash --rcfile ./env.bash -i || exit -1
+    elif [[ "$PYTHON_VERSION" == "2" ]]; then
         echo "***INFO | Machine has Python2 as default"
         # we need to pass "bash --rcfile ./env.bash" as single argument to scl command
         CMD_ARR=("scl" "enable" "rh-python36" "bash --rcfile ./env.bash -i")
+        export SCL_PYTHON_ENABLED=1
         echo "Spawning new shell : ${CMD_ARR[@]}"
-        "${CMD_ARR[@]}"
+        "${CMD_ARR[@]}" || exit -1
     else
-        echo "Error: $toolName | swapingNewShell | Cannot detect python2 or python3"
+        echo "Error: sbe-workon-utils | swapingNewShell          | Cannot detect python2 or python3"
         exit -1
     fi
-}
-
-# Fucntion to activate the Python virtual environment
-activatePythonVenv()
-{
-    echo "Activating pyton venv..."
-    if [ "$SCL_PYTHON_ENABLED" == 1 ]; then
-        virtualenv $SBEROOT_PYTHON_ENV --prompt="SBE" || SS_1=0
-    elif [ "$SCL_PYTHON_ENABLED" == 0 ]; then
-        python3 -m venv $SBEROOT_PYTHON_ENV --prompt="SBE"
-    else
-        echo "Error: venv-python | activatePythonVenv | SCL_PYTHON_ENABLED is not defined"
-        exit -1
-    fi
-    source $SBEROOT_PYTHON_ENV/bin/activate
 }
 
 # Function for install required packages which is their in requirements.txt
 installRequiredPackages()
 {
     echo "Installing Required packages..."
-    CMD="pip install -r $SBEROOT_PUB/src/tools/install/requirements.txt"
-    echo $CMD
-    $CMD || exit -1
-}
 
+    # Check the SCL is enable, if SCL is enable python3 default path /opt/rh/rh-python36/root/usr/bin/python3
+    if [ "$SCL_PYTHON_ENABLED" == 1 ]; then
+        # default python 2 scl, Intstalling packages in $HOME/.local_rh_python36/ path
+        # --no-warn-script-location supress the warning message for changing pythonuserbase location
+        CMD="pip install -r $SBEROOT_PUB/src/tools/install/requirements.txt --user --no-warn-script-location"
+     elif [ "$SCL_PYTHON_ENABLED" == 0 ]; then
+        # default python 3 path /user/bin/python3 or /bin/python3, Installing packages in $HOME/.local/
+        CMD="python3 -m pip install -r $SBEROOT_PUB/src/tools/install/requirements.txt --user"
+    else
+        echo "Error: sbe-workon-utils | installRequiredPackages | SCL_PYTHON_ENABLED is not defined"
+        exit -1
+    fi
+
+    echo $CMD
+    $CMD || {
+        if (($? != 0)); then
+            echo "Error: sbe-workon-utils | installRequiredPackages  | Failure: $?. Please do workon again."
+        fi
+        exit -1
+    }
+}
