Support compilation of sbe on LoP
This commit is to enable compilation of SBE on Linux on Power systems(LoP).

The location of the ppetool/signing tool binaries has been set based on the
architecture of the build system.

Change-Id: Ibdcf74079531655cfd34ff8fc8389270f4c55431
Reviewed-on: http://rchgit01.rchland.ibm.com/gerrit1/c/hw/sbe/+/175209
Reviewed-by: Akhilesh S <akhis023@in.ibm.com>
Tested-by: Jenkins Server <pfd-jenkins+hostboot@us.ibm.com>
Reviewed-by: Joseph J McGill <jmcgill@us.ibm.com>
Reviewed-by: Rajees P P <rajerpp1@in.ibm.com>

diff --git a/public/src/tools/utils/sbe/venv-utils b/public/src/tools/utils/sbe/venv-utils
--- a/public/src/tools/utils/sbe/venv-utils
+++ b/public/src/tools/utils/sbe/venv-utils
@@ -88,6 +88,16 @@ venvActivate()
 # Function for install required packages which is their in requirements.txt
 installRequiredPackages()
 {
+    echo "Update pip..."
+    CMD="python3 -m pip install --upgrade pip --no-cache-dir"
+    echo $CMD
+    $CMD || {
+        if (($? != 0)); then
+            echo "Error: venv-utils | installRequiredPackages  | Failure: $?"
+        fi
+        exit 1
+    }
+
     echo "Installing Required packages..."
     CMD="python3 -m pip install --no-cache-dir"
     CMD="$CMD -r $SBEROOT_PUB/src/tools/install/buildtoolrequirements.txt      \
